package university.domain.model;

public enum School {
    SCHOOL_OF_GEOLOGY, SCHOOL_OF_ENERGY, SCHOOL_OF_INFORMATION_TECHNOLOGIES,
    SCHOOL_OF_NATURAL_AND_SOCIAL_SCIENCES, BUSINESS_SCHOOL, SCHOOL_OF_ECONOMICS, MARITIME_ACADEMY,
    SCHOOL_OF_APPLIED_MATHEMATICS, SCHOOL_OF_CHEMICAL_ENGINEERING, SCHOOL_OF_GREEN_TECHNOLOGIES;
}
